# import torch
# from transformers import GPT2Tokenizer, GPT2LMHeadModel

# # 1. Setup Device (Uses GPU if available, else CPU)
# device = "cuda" if torch.cuda.is_available() else "cpu"
# print(f"Running on: {device}")

# # 2. Load Model and Tokenizer
# # This will download about 500MB the first time you run it
# print("Loading model...")
# tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
# model = GPT2LMHeadModel.from_pretrained("gpt2").to(device)

# # 3. Your Prompt
# prompt = "The future of Artificial Intelligence is"

# # 4. Convert text to numbers (Tensors)
# inputs = tokenizer.encode(prompt, return_tensors="pt").to(device)

# # 5. Generate Text (Using 'Top-P' sampling for better results)
# print("Generating...")
# output = model.generate(
#     inputs, 
#     max_length=100,            # Length of the output
#     do_sample=True,            # Enable creative sampling
#     top_p=0.95,                # Nucleus sampling
#     top_k=50,                  # Top-K sampling
#     temperature=0.8,           # Creativity level
#     no_repeat_ngram_size=2     # Prevents loops
# )

# # 6. Convert numbers back to text
# result = tokenizer.decode(output[0], skip_special_tokens=True)

# print("\n--- RESULT ---")
# print(result)
import os
import requests
import time
import re
from flask import Flask, render_template, request, jsonify
from dotenv import load_dotenv

load_dotenv()
app = Flask(__name__)

# Correct 2026 Router URL
API_URL = "https://router.huggingface.co/hf-inference/models/openai-community/gpt2"
HF_TOKEN = os.getenv("HF_TOKEN")

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/generate', methods=['POST'])
def generate():
    # DEBUG: Check if token exists
    if not HF_TOKEN:
        print("DEBUG: HF_TOKEN IS MISSING!")
        return jsonify({'text': "Error: Token not found in settings.", 'stats': 'Error'}), 500

    start_time = time.time()
    data = request.json
    prompt = data.get('prompt', '')
    
    # Standard headers for Hugging Face
    headers = {"Authorization": f"Bearer {HF_TOKEN}"}
    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 150, 
            "do_sample": True, 
            "temperature": 0.8,
            "return_full_text": False
        }
    }

    try:
        # This is where the actual generation request happens
        response = requests.post(API_URL, headers=headers, json=payload)
        
        if response.status_code != 200:
            print(f"API Error: {response.text}")
            return jsonify({'text': f"API failed to generate: {response.text}", 'stats': 'Fail'}), 200
            
        result = response.json()
        
        # Extract the generated text
        if isinstance(result, list) and len(result) > 0:
            generated_output = result[0].get('generated_text', '')
        else:
            generated_output = "No text was generated by the model."

        return jsonify({
            'text': generated_output,
            'stats': f"{round(time.time() - start_time, 2)}s",
            'word_count': len(generated_output.split())
        })

    except Exception as e:
        print(f"CRASH: {str(e)}")
        return jsonify({'text': f"System Crash: {str(e)}", 'stats': 'Error'}), 500

if __name__ == '__main__':
    app.run()